[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "diacritics_restoration"
version = "0.1.0"
description = "A project for restoring diacritics in Polish text."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    "datasets",
    "evaluate",
    "huggingface-hub",
    "httpx",
    "jiwer",
    "matplotlib",
    "numpy",
    "pandas",
    "pillow",
    "pyarrow",
    "pyyaml",
    "rapidfuzz",
    "requests",
    "rich",
    "scikit-learn",
    "seaborn",
    "sympy",
    "torch",
    "torchinfo",
    "torchvision",
    "tqdm",
    "transformers",
    "typer",
    "unidecode",
    "matplotlib-inline"
]